[package]
name = "stars-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]
path = "src/main.rs"

[dependencies]
softbuffer = "0.4.1"
wasm-bindgen = "0.2.91"
winit = "0.29.14"
